# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  batch: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    buildContext: '**'
    tags: latest

- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerHub

- task: Docker@2
  displayName: Push to Docker Hub
  inputs:
    command: push
    containerRegistry: DockerHub
    repository: 'jensras/CoolWebsite'
    tags: latest